  btc:
    image: ghcr.io/mmfpsolutions/bitcoin-knots:latest
    container_name: btc
    network_mode: host
    stop_grace_period: 120s
    volumes:
      - /data/btc/data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"  
    restart: unless-stopped
